echo "Terminal Go tools:"
echo " * mockery: generate testify/mock mocks from interfaces"
echo "Terminal Docker tools aliases:"
echo " * dive: inspect the layers of a Docker image"
echo " * ld: run lazydocker in a container"
