#!/bin/bash

docker run --rm --privileged -v `pwd`:/tmp/app \
    --entrypoint buildctl-daemonless.sh \
    moby/buildkit \
    build \
    --frontend=dockerfile.v0 --local context=/tmp/app --local dockerfile=/tmp/app \
    --output type=image,name=$IMAGE_NAME \
    --opt build-arg:BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --opt build-arg:VCS_REF=`git rev-parse --short HEAD`