name: labels
on:
  push:
    branches: ["master"]
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
